source "http://rubygems.org"

# Sass/Compass
gem "sass-globbing", "~> 1.1.0"
gem "sass-css-importer", "~> 1.0.0.beta.0"
gem "compass", "~> 1.0.0.alpha.19"
gem "breakpoint", "~> 2.4.2"
gem "ceaser-easing", "~> 0.7"
gem "SassyLists", "~> 1.0.0"
gem "toolkit", "~> 2.0.1"
